### ISSUE TITLE
Observation: Error

### ISSUE THREAD

**Issue by Junzhou-Chen** [PJLab-ADG/DriveLikeAHuman#12]
Hi, your work is amazing! However I have notice that I use chatgpt to grenerate the thought, will often return "Observation: Check your output and make sure it conforms the format instructions!"
Have you tried other ways to better constrain the output of large models?

**Comment by zijinoier** [comment]
Hi, this message is shown as the output of ChatGPT doesn't meet the required input format for tool usage.

This isn't an error, but an assistant message telling ChatGPT to generate a new message to fit the tool's format.
For more information, please refer to https://python.langchain.com/docs/modules/agents/how_to/handle_parsing_errors.

This is one of the most worked parsing error handle message we have tried.
