### ISSUE TITLE
Error with http://llama-adapter.opengvlab.com/

### ISSUE THREAD

**Issue by LW0214** [PJLab-ADG/DriveLikeAHuman#13]
Hi, thank you so much for your amazing work! I'm experimenting with the `CaseReasoning` ipynb, where a few weeks ago, it's able to run smoothly locally. Yet now, when I try to run `client = Client("http://llama-adapter.opengvlab.com/")`, it generates an error 
ValueError: Could not get Gradio config from: http://llama-adapter.opengvlab.com/

And it appears that http://llama-adapter.opengvlab.com/ is now down? Do you happen to know any updates to this? Thank you so much!

**Comment by zijinoier** [comment]
We've also just become aware that http://llama-adapter.opengvlab.com/ service is currently down. The llama-adapter is a third-party api that we utilize, and unfortunately, we **don't have information regarding the reason for the downtime or when it might be resolved**.

However, with the release of GPT-4V, we believe that you can achieve similar functionality using GPT-4V directly. For more information on how to implement this and for further details, please r**efer to our latest work and the associated paper available** at: https://github.com/PJLab-ADG/GPT-4V-for-AD

**Comment by IdoCohenAB** [comment]
any news regarding the llamma=adapter service?

**Comment by zijinoier** [comment]
try http://imagebind-llm.opengvlab.com/

**Comment by IdoCohenAB** [comment]
thanks. tried changing in CaseReasoning notebook but got an error
 `client = Client("http://imagebind-llm.opengvlab.com/")
llama_result = client.predict(
    image_url,  # str representing input in 'Input' Image component
    "Describe the picture as details as possible and focus on the main object.Do not describe what you don't see. The objects in the picture are moving.",    
    512,  # int | float representing input in 'Max length' Slider component
    0.1,  # int | float representing input in 'Temperature' Slider component
    0.75,  # int | float representing input in 'Top p' Slider component
    fn_index=1
)
llama_result`

return IndexError: list index out of range
