### ISSUE TITLE
复现出错

### ISSUE THREAD

**Issue by AHPUymhd** [PJLab-ADG/DriveLikeAHuman#14]
Hello, I have followed the method in this article to execute python HELLM.py,The following situation occurred, it kept running and got stuck here
![image](https://github.com/PJLab-ADG/DriveLikeAHuman/assets/72792297/cb95ed00-b7ac-48f5-a661-8eaed15c7170)

**Comment by AHPUymhd** [comment]
@zijinoier Could you please help me check what the problem is  thank  you  very  much

**Comment by zijinoier** [comment]
try this environment:
```
gymnasium            0.28.1
moviepy              1.0.3
Python               3.8.16
```
