### ISSUE TITLE
Change the large model

### ISSUE THREAD

**Issue by AHPUymhd** [PJLab-ADG/DriveLikeAHuman#15]
Does your project support the replacement of large language models, such as replacing gpt3.5 in the project with the ChatGlm3 large model? Because our school does not have the conditions to unlock the restrictions of gpt3.5, that is, it does not have a credit card to upgrade the openai account. Thank you.

**Comment by AHPUymhd** [comment]
@zijinoier thank  you

**Comment by zijinoier** [comment]
Please refer to this comment in issue #5 : https://github.com/PJLab-ADG/DriveLikeAHuman/issues/5#issuecomment-1693058019
