### ISSUE TITLE
Rate Limit Error from Chatgpt

### ISSUE THREAD

**Issue by wangyixu14** [PJLab-ADG/DriveLikeAHuman#16]
Hi there,

Thanks for sharing this great work. 
The code worked well when I first tried it one month ago. However, I tried it yesterday and got the Rate Limit Error from the Openai API after running up to 10 frames; therefore, the simulation terminated. I wonder whether you have had the same error as mine recently and any thoughts on this error. Looking forward to your reply.

Best,
Yixuan

**Comment by AHPUymhd** [comment]
> Hi there,
> 
> Thanks for sharing this great work. The code worked well when I first tried it one month ago. However, I tried it yesterday and got the Rate Limit Error from the Openai API after running up to 10 frames; therefore, the simulation terminated. I wonder whether you have had the same error as mine recently and any thoughts on this error. Looking forward to your reply.
> 
> Best, Yixuan

creat a account is ok    maybe api_key is limited  if free and the RPM is 3

**Comment by wangyixu14** [comment]
Could you please be more specific? I am using the API key from my account which is definitely not free. What's RPM and how should I adjust it?

**Comment by AHPUymhd** [comment]
> Could you please be more specific? I am using the API key from my account which is definitely not free. What's RPM and how should I adjust it?

RPM is Request Per Minute   , if you are not free the limit is not on the RPM,and now i run it is also so slow ,I wonder if you have the same problem

**Comment by zijinoier** [comment]
> Could you please be more specific? I am using the API key from my account which is definitely not free. What's RPM and how should I adjust it?

I think you can refer to https://platform.openai.com/docs/guides/rate-limits/ page for the full imforamtion.

Rate limits are measured in five ways: RPM (requests per minute), RPD (requests per day), TPM (tokens per minute), TPD (tokens per day), and IPM (images per minute).
