### ISSUE TITLE
The environment runs very slowly, and it takes a few minutes for the vehicle to move

### ISSUE THREAD

**Issue by AHPUymhd** [PJLab-ADG/DriveLikeAHuman#17]
When i run python HELLM.py ,The environment runs very slowly, and it takes a few minutes for the vehicle to move,And then stuck on this interface without moving，my openai account is already have $8.78， but why is the program stuck and not moving
like this
![Uploading image.png…]()

**Comment by AHPUymhd** [comment]
![image](https://github.com/PJLab-ADG/DriveLikeAHuman/assets/72792297/fc76dd5c-2801-443a-a8b1-de3036e48e34)

@zijinoier please help me!!

**Comment by zijinoier** [comment]
which model do you use? GPT-3.5 or GPT-4?
by the way, are you using Azure or Openai API?

**Comment by AHPUymhd** [comment]
请问你是中国的吗，是的话可以加我qq1848795229&nbsp; &nbsp;我们可以交流一下，我也有点问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PJLab-ADG/DriveLikeAHuman"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月7日(星期四) 下午3:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PJLab-ADG/DriveLikeAHuman] The environment runs very slowly, and it takes a few minutes for the vehicle to move (Issue #17)





 
which model do you use? GPT-3.5 or GPT-4?
 by the way, are you using Azure or Openai API?

**Comment by AHPUymhd** [comment]
model is  gpt-3.5-turbo-16k-0613 and  i use Openai API，thanks

**Comment by AHPUymhd** [comment]
> which model do you use? GPT-3.5 or GPT-4? by the way, are you using Azure or Openai API?

model is gpt-3.5-turbo-16k-0613 and i use Openai API，thanks

**Comment by AHPUymhd** [comment]
> which model do you use? GPT-3.5 or GPT-4? by the way, are you using Azure or Openai API?

![image](https://github.com/PJLab-ADG/DriveLikeAHuman/assets/72792297/edad8e09-75fe-4bbc-b8cd-da49f88a84e0)
just like this   ，is the error with this？

**Comment by wangyixu14** [comment]
I am facing the same problem here, along with the [rate limit error](https://github.com/PJLab-ADG/DriveLikeAHuman/issues/16).

**Comment by zijinoier** [comment]
You're running the code without any problems.

Generally speaking, **it takes about 30 seconds to several minutes to run a decision step** (you can see vehicle move a time in the highway-env gui), and it's normal for the GUI to show "not responding" when the driver agent is making decisions.
As You can see the output of the driver agent executing the ReAct process in the runtime terminal, if it's outputing then the program is still working properly.

Your fee is also the cost of api calls to the openai api.
