### ISSUE TITLE
It doesn't work as smoothly as the video you showed

### ISSUE THREAD

**Issue by AHPUymhd** [PJLab-ADG/DriveLikeAHuman#18]
Thank you for the open source spirit, and the ideas in the paper are great，However, I have always had a problem in running your code, and I have asked questions several times, but the problem has not been solved, so I would like to ask you in detail.Here is the same code as yours
![image](https://github.com/PJLab-ADG/DriveLikeAHuman/assets/72792297/7866be78-d3e5-45e0-bb48-db6f82c971e5)
![image](https://github.com/PJLab-ADG/DriveLikeAHuman/assets/72792297/87f1ebab-221a-4cac-b632-86e33c758878)
The results are as follows
![ZYZUD)K2B@O5S%GPY@ KG L](https://github.com/PJLab-ADG/DriveLikeAHuman/assets/72792297/96f5d1bf-0145-483f-a655-37ae1eda034b)
Just keep stuck like this, and then wait until the final decision is made before running, and then keep stuck waiting for running，
I was wondering if this is normal, because I saw how smooth your demo videos were
So the question was raised，I think there are the following anomalies in conda, and I will list them one by one. Please kindly help me to see which aspects are the problems
![image](https://github.com/PJLab-ADG/DriveLikeAHuman/assets/72792297/a802e41b-5794-45b8-9712-a1a5cae45af0)
![image](https://github.com/PJLab-ADG/DriveLikeAHuman/assets/72792297/7d4e07f5-b71d-4207-b4e2-e9398e81c854)
![image](https://github.com/PJLab-ADG/DriveLikeAHuman/assets/72792297/4972bca7-d6a7-403a-b6d1-ef64a1c24652)
![image](https://github.com/PJLab-ADG/DriveLikeAHuman/assets/72792297/4405d973-b1f5-407b-91d2-b08374ed79e6)
It is probably the above exceptions, which have warning errors, and there are many repeated reasoning processes, I do not know whether these problems cause the simulator to stall and not run smoothly，I would really appreciate your help！！！

**Comment by AHPUymhd** [comment]
@zijinoier

**Comment by zijinoier** [comment]
@AHPUymhd I have been busy this week, I plan to check this issue next week.
Thanks for your patient and understanding.

**Comment by AHPUymhd** [comment]
> @AHPUymhd I have been busy this week, I plan to check this issue next week. Thanks for your patient and understanding.

Thank you very much for your reply and look forward to your help

**Comment by AHPUymhd** [comment]
@zijinoier Thank you very much for your reply and look forward to your help

**Comment by zijinoier** [comment]
Hi, your program seems working fine, and I have to clear up one of your misunderstandings, **the video shown in the README is not rendered in real time, but is a visualisation after running a whole simulation.**

Generally speaking, **it takes about 30 seconds to several minutes to run a decision step** (you can see vehicle move a time in the highway-env gui), and it's normal for the GUI to show "not responding". You can see the output of the driver agent executing the ReAct process in the runtime terminal, if it's outputing then the program is working.

**Comment by AHPUymhd** [comment]
> Hi, your program seems working fine, and I have to clear up one of your misunderstandings, **the video shown in the README is not rendered in real time, but is a visualisation after running a whole simulation.**
> 
> Generally speaking, **it takes about 30 seconds to several minutes to run a decision step** (you can see vehicle move a time in the highway-env gui), and it's normal for the GUI to show "not responding". You can see the output of the driver agent executing the ReAct process in the runtime terminal, if it's outputing then the program is working.

Thank you very much for your answer and help me explain this problem that has been bothering me for a long time. Thank you very much
