### ISSUE TITLE
Experimental data

### ISSUE THREAD

**Issue by AHPUymhd** [PJLab-ADG/DriveLikeAHuman#20]
I would like to ask why your experimental data is not reflected in the paper, such as the success rate of 30s in the environment of road 4 and density 1，We look forward to hearing from you！

**Comment by AHPUymhd** [comment]
@zijinoier

**Comment by zijinoier** [comment]
Please kindly refer to our following work DiLu.

Specially, this issue https://github.com/PJLab-ADG/DiLu/issues/10 

Thanks.
