### ISSUE TITLE
gymnasium.error.NameNotFound: Environment `highway` doesn't exist.

### ISSUE THREAD

**Issue by ShiXiangXiang123** [PJLab-ADG/DriveLikeAHuman#4]
![image](https://github.com/PJLab-ADG/DriveLikeAHuman/assets/107922257/93f55714-20a3-41ee-82ea-812f7a4e0251)

**Comment by zijinoier** [comment]
Hi, You need to install `highway-env` by run
```bash
pip install highway-env
```

**Comment by ShiXiangXiang123** [comment]
> Hi, You need to install `highway-env` by run
> 
> ```shell
> pip install highway-env
> ```
Thank you very much for your answer, I'll give it a try now. ...

**Comment by ShiXiangXiang123** [comment]
> Hi, You need to install `highway-env` by run
> 
> ```shell
> pip install highway-env
> ```
![LS GJI31S~VMF2P`ECB`3I9](https://github.com/PJLab-ADG/DriveLikeAHuman/assets/107922257/5f4314e0-467a-476a-a18c-1bfe1eee01b1)
![)L6X)%M@4(%Z55JQV(G(_X5](https://github.com/PJLab-ADG/DriveLikeAHuman/assets/107922257/b6868797-2ded-4193-8b7d-4a49f031824d)
请问这个问题要怎么才能解决！

**Comment by zijinoier** [comment]
See https://help.openai.com/en/articles/6891831-error-code-429-you-exceeded-your-current-quota-please-check-your-plan-and-billing-details
