### ISSUE TITLE
I want to use my own model, but I don't know how to modify 

### ISSUE THREAD

**Issue by ShiXiangXiang123** [PJLab-ADG/DriveLikeAHuman#5]
![image](https://github.com/PJLab-ADG/DriveLikeAHuman/assets/107922257/64ce92e2-d1b7-4b47-94ff-febab9ac1858)

**Comment by zijinoier** [comment]
To use ChatGLM6B, please refer these two links:
https://python.langchain.com/docs/integrations/llms/chatglm
https://zhuanlan.zhihu.com/p/630147161

FYI, We have not tried ChatGLM-6B and cannot guarantee its validity or reliability.

**Comment by ShiXiangXiang123** [comment]
> To use ChatGLM6B, please refer these two links: https://python.langchain.com/docs/integrations/llms/chatglm https://zhuanlan.zhihu.com/p/630147161
> 
> FYI, We have not tried ChatGLM-6B and cannot guarantee its validity or reliability.

如果想使用自己微调的模型，要怎么修改呢

**Comment by zijinoier** [comment]
While incorporating user fine-tuned models isn't our primary focus, we warmly welcome you to implement this feature and submit a pull request. 
Your contribution would be greatly appreciated! 😊

**Comment by lzf18** [comment]
> > To use ChatGLM6B, please refer these two links: https://python.langchain.com/docs/integrations/llms/chatglm https://zhuanlan.zhihu.com/p/630147161
> > FYI, We have not tried ChatGLM-6B and cannot guarantee its validity or reliability.
> 
> 如果想使用自己微调的模型，要怎么修改呢


可以现在本地部署，然后HELLM.py里修改下llm的创建即可。
elif OPENAI_CONFIG['OPENAI_API_TYPE'] == 'chatglm':
    endpoint_url = OPENAI_CONFIG["ENDPOINT_URL"]
    llm = ChatGLM(
        endpoint_url=endpoint_url,
        max_token=80000,
        history=[],
        top_p=1,
        model_kwargs={"sample_model_args": False},
    )

不过用其他大模型，效果不一定好，模型不一定能理解这个prompt。目前来看chatpgt是最强的

**Comment by AHPUymhd** [comment]
> > > To use ChatGLM6B, please refer these two links: https://python.langchain.com/docs/integrations/llms/chatglm https://zhuanlan.zhihu.com/p/630147161
> > > FYI, We have not tried ChatGLM-6B and cannot guarantee its validity or reliability.
> > 
> > 
> > 如果想使用自己微调的模型，要怎么修改呢
> 
> 可以现在本地部署，然后HELLM.py里修改下llm的创建即可。 elif OPENAI_CONFIG['OPENAI_API_TYPE'] == 'chatglm': endpoint_url = OPENAI_CONFIG["ENDPOINT_URL"] llm = ChatGLM( endpoint_url=endpoint_url, max_token=80000, history=[], top_p=1, model_kwargs={"sample_model_args": False}, )
> 
> 不过用其他大模型，效果不一定好，模型不一定能理解这个prompt。目前来看chatpgt是最强的

请问可以看一下您的代码吗，就是换成CHATGLM的那一部分代码，我按照您上面的代码没改成功
