### ISSUE TITLE
do we really need to interact with the AD system for several cycles ?

### ISSUE THREAD

**Issue by wzn0828** [PJLab-ADG/DriveLikeAHuman#6]
Do we really need to interact with the AD system for several cycles ?

If so, the questions we asked the AD system must influence the results.

**Comment by zijinoier** [comment]
Apologies for any confusion. I'm not fully certain about the specific context of your question, particularly regarding the terms "AD system" and "several cycles."

Nevertheless, I would suggest delving into our research paper for a more comprehensive understanding. It should offer valuable insights that could address your inquiries： https://arxiv.org/pdf/2307.07162

**Comment by wzn0828** [comment]
![image](https://github.com/PJLab-ADG/DriveLikeAHuman/assets/29533484/efcac63f-594b-41fd-b646-2eb644c71039)

Do we really need to interact with the Autonomous Driving system (GPT3.5) for several cycles?
As in this image, we interact with the AD 8 cycles.

**Comment by zijinoier** [comment]
Well, this is because we adopts ReAct logic in our decision-making.
Please refer this link for more infos about ReAct: https://react-lm.github.io/
