### ISSUE TITLE
Is there no self-reflection module?

### ISSUE THREAD

**Issue by histfuture** [PJLab-ADG/DriveLikeAHuman#7]
Where are the 'Self-reflection' and 'Memories' modules mentioned in the paper?

**Comment by zijinoier** [comment]
We have not open-sourced the 'Self-reflection' and 'Memories' modules at the moment. 
The specific release date for these modules is yet to be determined, and we apologize for any inconvenience caused.

**Comment by ShiXiangXiang123** [comment]
> 我们目前还没有开源“自我反思”和“记忆”模块。这些模块的具体发布日期尚未确定，对于由此造成的任何不便，我们深表歉意。

那你们的精神可真不如马斯克！！！！！1

**Comment by Meta-YZ** [comment]
> We have not open-sourced the 'Self-reflection' and 'Memories' modules at the moment. The specific release date for these modules is yet to be determined, and we apologize for any inconvenience caused.

Hi！Thank you very much for your work and for making it open source. I am also very interested in your implementation of ‘Self-reflection and Memories’ and hope to see it in the future. Will all of this code be open sourced eventually?

**Comment by zijinoier** [comment]
> Hi！Thank you very much for your work and for making it open source. I am also very interested in your implementation of ‘Self-reflection and Memories’ and hope to see it in the future. Will all of this code be open sourced eventually?

Thank you for your kind words and for showing interest in our open-source project. 
We're planning to release the 'Self-reflection and Memories' modules, but we're currently optimizing them for better performance.
We're aiming to open-source them within the next several months, so stay tuned for updates. Your patience is much appreciated.

**Comment by Meta-YZ** [comment]
> > Hi！Thank you very much for your work and for making it open source. I am also very interested in your implementation of ‘Self-reflection and Memories’ and hope to see it in the future. Will all of this code be open sourced eventually?
> 
> Thank you for your kind words and for showing interest in our open-source project. We're planning to release the 'Self-reflection and Memories' modules, but we're currently optimizing them for better performance. We're aiming to open-source them within the next several months, so stay tuned for updates. Your patience is much appreciated.

OK, Thanks a lot!
