### ISSUE TITLE
我自己换了模型，如下图所示，但是出问题了，请求指教

### ISSUE THREAD

**Issue by ShiXiangXiang123** [PJLab-ADG/DriveLikeAHuman#8]
![}965F(GZLS4YY4 E{HZ0S$W](https://github.com/PJLab-ADG/DriveLikeAHuman/assets/107922257/58b99362-a778-4b35-830a-e3d3e9bbf5cc)

**Comment by zijinoier** [comment]
We genuinely appreciate your dedication to incorporating the `gpt2-ggml` model into our project. 

However, it's important to note that we haven't yet tested or employed this model as our language model (LLM). Consequently, we regret that we're unable to provide assistance with the particular issue you're encountering related to the `gpt2-ggml` model's usage within our projects.

We recommend seeking help for your query within the `gpt2-ggml` community or its GitHub repository,

**Comment by zijinoier** [comment]
We genuinely appreciate your dedication to incorporating the `gpt2-ggml` model into our project. 

However, it's important to note that we haven't yet tested or employed this model as our language model (LLM). Consequently, we regret that we're unable to provide assistance with the particular issue you're encountering related to the `gpt2-ggml` model's usage within our projects.

We recommend seeking help for your query within the `gpt2-ggml` community or its GitHub repository,
